plugins {
	id 'com.android.application'
}

android {
	compileSdk 34
	
	useLibrary 'org.apache.http.legacy'
	
	defaultConfig {
		applicationId "com.nexusteam.blacklogics"
		namespace "com.nexusteam.blacklogics"
		minSdkVersion 21
		targetSdkVersion 35
		versionCode 15564
		versionName "0.0.6 alpha6"
	}
	
	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
	}
}

dependencies {
	implementation fileTree(dir: 'libs', include: ['*.jar'])
	implementation 'androidx.appcompat:appcompat:1.7.1'
	implementation 'com.google.android.material:material:1.12.0'
	implementation 'com.google.android.gms:play-services-ads:23.4.0'
	implementation 'com.google.code.gson:gson:2.11.0'
	implementation 'de.hdodenhof:circleimageview:3.1.0'
	implementation 'com.airbnb.android:lottie:6.5.2'
	implementation 'com.google.guava:guava:31.1-android'
	implementation 'com.github.angads25:filepicker:1.1.1'
	implementation 'com.github.angads25:filepicker:1.1.1'
	implementation 'com.github.angads25:filepicker:1.1.1'
}
